version: '3.8'

services:
  frontend:
    build:
      context: ./solar_app
      dockerfile: Dockerfile
    ports:
      - "8101:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./solar_server
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: solar_db
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: solar_db
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:

